apiVersion: v1
kind: ConfigMap

metadata:
  name: auth-service-config
  namespace: event-platform

data:
  SERVER_PORT: "8082"

  CONFIG_SERVER_URL: "http://config-server:8888"

  AUTH_DB_URL: "jdbc:postgresql://postgres:5432/auth"
  AUTH_DB_USERNAME: "postgres"
  AUTH_DB_PASSWORD: "postgres"