apiVersion: v1
kind: ConfigMap

metadata:
  name: config-server-config
  namespace: event-platform

data:
  SERVER_PORT: "8888"

  GIT_REPO_URI: "https://github.com/anujyadav11/event-platform-config.git"
  GIT_DEFAULT_BRANCH: "main"