apiVersion: v1
kind: ConfigMap

metadata:
  name: notification-service-config
  namespace: event-platform

data:
  SERVER_PORT: "8086"

  CONFIG_SERVER_URL: "http://config-server:8888"

  NOTIFICATION_DB_URL: "jdbc:postgresql://postgres:5432/notification"
  NOTIFICATION_DB_USERNAME: "postgres"
  NOTIFICATION_DB_PASSWORD: "postgres"