apiVersion: v1
kind: ConfigMap

metadata:
  name: platform-config
  namespace: event-platform

data:
  SPRING_PROFILES_ACTIVE: kubernetes

  # 👇 Add this
  SPRING_CONFIG_IMPORT: optional:configserver:http://app-config-server:8888

  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  REDIS_HOST: redis
  REDIS_PORT: "6379"

  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"

  EUREKA_SERVER_URL: http://app-discovery-server:8761/eureka/

  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"

  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans