apiVersion: apps/v1
kind: Deployment

metadata:
  name: app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: delivery-service

  template:
    metadata:
      labels:
        app: delivery-service

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: app

          image: delivery-service:1.0
          imagePullPolicy: IfNotPresent

          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 15

          ports:
            - containerPort: 8086

          envFrom:
            - configMapRef:
                name: platform-config
            - configMapRef:
                name: delivery-service-config

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
