apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: event-platform

spec:
  replicas: 1

  selector:
    matchLabels:
      app: zipkin

  template:
    metadata:
      labels:
        app: zipkin

    spec:
      containers:
        - name: zipkin

          image: openzipkin/zipkin:3

          ports:
            - containerPort: 9411

          livenessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 15
            periodSeconds: 5

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"