apiVersion: v1
kind: ConfigMap

metadata:
  name: api-gateway-config
  namespace: event-platform

data:
  SERVER_PORT: "8080"

  CONFIG_SERVER_URL: "http://config-server-spring-boot-app:8888"

  EUREKA_SERVER_URL: "http://discovery-server-spring-boot-app:8761/eureka"