- op: replace
  path: /spec/selector/matchLabels/app
  value: api-gateway

- op: replace
  path: /spec/template/metadata/labels/app
  value: api-gateway

- op: replace
  path: /spec/template/spec/containers/0/image
  value: api-gateway:1.0

- op: replace
  path: /spec/template/spec/containers/0/ports/0/containerPort
  value: 8080

- op: add
  path: /spec/template/spec/containers/0/envFrom/1
  value:
    configMapRef:
      name: api-gateway-config