apiVersion: apps/v1
kind: Deployment

metadata:
  name: pricing-service
  namespace: eventstream

  labels:
    app: pricing-service
    app.kubernetes.io/name: pricing-service
    app.kubernetes.io/part-of: eventstream

spec:
  replicas: 1

  selector:
    matchLabels:
      app: pricing-service

  template:
    metadata:
      labels:
        app: pricing-service
        app.kubernetes.io/name: pricing-service
        app.kubernetes.io/part-of: eventstream

    spec:
      containers:
        - name: pricing-service

          image: 226932643820.dkr.ecr.ap-south-1.amazonaws.com/eventstream/pricing-service:1.0.1

          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8089
              protocol: TCP

          env:

            # Spring Boot
            - name: SERVER_PORT
              value: "8089"

            # Config Server
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"

            # Zipkin is intentionally not deployed in AWS.
            - name: MANAGEMENT_TRACING_ENABLED
              value: "false"

            # Eureka
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka/"

            # Redis
            - name: REDIS_HOST
              value: "redis.eventstream-infra"

            - name: SPRING_DATA_REDIS_HOST
              value: "redis.eventstream-infra"

            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

            # Kafka
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.eventstream-infra:29092"

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.eventstream-infra:29092"

            # JVM
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError"

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "768Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http

            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http

            initialDelaySeconds: 70
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          securityContext:
            allowPrivilegeEscalation: false

            capabilities:
              drop:
                - ALL
