apiVersion: v1
kind: Service

metadata:
  name: discovery-server
  namespace: eventstream

  labels:
    app: discovery-server
    app.kubernetes.io/name: discovery-server
    app.kubernetes.io/part-of: eventstream

spec:
  type: ClusterIP

  selector:
    app: discovery-server

  ports:
    - name: http
      port: 8761
      targetPort: http
      protocol: TCP