apiVersion: v1
kind: Namespace
metadata:
  name: eventstream
  labels:
    project: real-time-event-streaming-platform
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: eventstream-infra
  labels:
    project: real-time-event-streaming-platform
    environment: production