apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  # PostgreSQL
  - postgres/secret.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml

  # Redis
  - redis/deployment.yaml
  - redis/service.yaml

  # Kafka
  - kafka/pvc.yaml
  - kafka/deployment.yaml
  - kafka/service.yaml

  # Kafka UI
  - kafka-ui/deployment.yaml
  - kafka-ui/service.yaml

  # Zipkin
  - zipkin/deployment.yaml
  - zipkin/service.yaml

  # Prometheus
  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml

  # Grafana
  - grafana/datasource-configmap.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml