apiVersion: v1
kind: ConfigMap

metadata:
  name: order-service-config
  namespace: event-platform

data:
  SERVER_PORT: "8081"
  SPRING_CONFIG_IMPORT: "configserver:http://app-config-server:8888"
  PRICING_SERVICE_BASE_URL: "http://app-pricing-service:8089"
