apiVersion: v1
kind: ConfigMap

metadata:
  name: auth-service-config
  namespace: event-platform

data:
  SERVER_PORT: "8081"

  CONFIG_SERVER_URL: "http://config-server-spring-boot-app:8888"

  EUREKA_SERVER_URL: "http://discovery-server-spring-boot-app:8761/eureka"

  AUTH_DB_URL: "jdbc:postgresql://postgres:5432/auth"

  AUTH_DB_USERNAME: "postgres"

  AUTH_DB_PASSWORD: "postgres"

  REDIS_HOST: "redis"

  REDIS_PORT: "6379"