services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: event_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro

    networks:
      - event-platform-network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d event_platform" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis-data:/data

    networks:
      - event-platform-network

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    restart: unless-stopped

    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      # KRaft Configuration
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:29092,CONTROLLER://:9093

      # What clients see
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka-data:/var/lib/kafka/data

    networks:
      - event-platform-network

    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9092 || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 10

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui

    restart: unless-stopped

    depends_on:
      - kafka

    ports:
      - "8085:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

    networks:
      - event-platform-network

volumes:
  postgres-data:
  redis-data:
  kafka-data:

networks:
  event-platform-network:
    driver: bridge
