apiVersion: v1
kind: ConfigMap

metadata:
  name: order-service-config
  namespace: event-platform

data:
  SERVER_PORT: "8082"

  CONFIG_SERVER_URL: "http://config-server-spring-boot-app:8888"

  EUREKA_SERVER_URL: "http://discovery-server-spring-boot-app:8761/eureka"

  ORDER_DB_URL: "jdbc:postgresql://postgres:5432/orders"
  ORDER_DB_USERNAME: "postgres"
  ORDER_DB_PASSWORD: "postgres"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"