- op: replace
  path: /metadata/name
  value: order-service-spring-boot-app

- op: replace
  path: /spec/selector/matchLabels/app
  value: order-service

- op: replace
  path: /spec/template/metadata/labels/app
  value: order-service

- op: replace
  path: /spec/template/spec/containers/0/name
  value: order-service

- op: replace
  path: /spec/template/spec/containers/0/image
  value: order-service:1.0

- op: replace
  path: /spec/template/spec/containers/0/ports/0/containerPort
  value: 8082

- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    configMapRef:
      name: order-service-config