apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway-sa.yaml
  - auth-service-sa.yaml
  - order-service-sa.yaml
  - inventory-service-sa.yaml
  - pricing-service-sa.yaml
  - payment-service-sa.yaml
  - notification-service-sa.yaml
  - delivery-service-sa.yaml
  - saga-orchestrator-sa.yaml
