apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: eventstream-infra

  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: eventstream

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: eventstream

    spec:
      containers:
        - name: postgres

          image: postgres:16

          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP

          env:
            - name: POSTGRES_DB
              value: event_platform

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d event_platform

            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d event_platform

            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/init-databases.sql
              subPath: init-databases.sql
              readOnly: true

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

        - name: postgres-init
          configMap:
            name: postgres-init