apiVersion: apps/v1
kind: Deployment

metadata:
  name: app

spec:
  selector:
    matchLabels:
      app: discovery-server

  template:
    metadata:
      labels:
        app: discovery-server

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: app
          image: discovery-server:1.0
          imagePullPolicy: IfNotPresent

          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 15

          envFrom:
            - configMapRef:
                name: platform-config
            - configMapRef:
                name: discovery-server-config
            - secretRef:
                name: platform-secret

        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health/readiness
        #     port: 8761

        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health/liveness
        #     port: 8761
