apiVersion: apps/v1
kind: Deployment

metadata:
  name: app

spec:
  selector:
    matchLabels:
      app: discovery-server

  template:
    metadata:
      labels:
        app: discovery-server

    spec:
      containers:
        - name: app

          image: discovery-server:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8761

          envFrom:
            - configMapRef:
                name: platform-config

            - configMapRef:
                name: discovery-server-config

            - secretRef:
                name: platform-secret