apiVersion: apps/v1
kind: Deployment

metadata:
  name: app

spec:
  replicas: 1
  revisionHistoryLimit: 2

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: app

  template:
    metadata:
      labels:
        app: app

    spec:
      containers:
        - name: app

          image: app:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: platform-config

         # readinessProbe:
            #httpGet:
             # path: /actuator/health/readiness
              #port: 8080
            #initialDelaySeconds: 20
            #periodSeconds: 10

          #livenessProbe:
            #httpGet:
             # path: /actuator/health/liveness
              #port: 8080
            #initialDelaySeconds: 40
            #kubectl kustomize k8s/base/services/discovery-serverperiodSeconds: 15

          resources:
            requests:
              cpu: 200m
              memory: 256Mi

            limits:
              cpu: 500m
              memory: 512Mi
