apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: event-platform
type: Opaque
stringData:
  POSTGRES_DB: event_platform
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres