apiVersion: apps/v1
kind: Deployment

metadata:
  name: app

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: websocket-service

  template:
    metadata:
      labels:
        app: websocket-service

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: app

          image: websocket-service:1.0
          imagePullPolicy: IfNotPresent

          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 15

          ports:
            - containerPort: 8088

          envFrom:
            - configMapRef:
                name: platform-config
            - configMapRef:
                name: websocket-service-config

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8088
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8088
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
