apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: event-platform

nameSuffix: -saga-orchestrator

resources:
  - ../../common/deployment
  - ../../common/service
  - configmap.yaml
  - pdb.yaml

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
