apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  namespace: eventstream
  labels:
    app: api-gateway

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway

          image: 226932643820.dkr.ecr.ap-south-1.amazonaws.com/eventstream/api-gateway:1.0.1

          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          env:
            - name: SERVER_PORT
              value: "8080"

            # Config Server
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"

            # Eureka
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka/"

            #JWT secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform-secret
                  key: JWT_SECRET

            # JVM
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "768Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3