apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: kafka-pvc
  namespace: eventstream-infra

  labels:
    app: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: eventstream

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: gp3

  resources:
    requests:
      storage: 20Gi