server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:https://github.com/anujyadav11/event-platform-config.git}
          default-label: ${CONFIG_REPO_LABEL:main}
          clone-on-start: true
          force-pull: true
          timeout: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
