apiVersion: apps/v1
kind: Deployment

metadata:
  name: app

spec:
  selector:
    matchLabels:
      app: config-server

  template:
    metadata:
      labels:
        app: config-server

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: app
          image: config-server:1.0

          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 15

          ports:
            - containerPort: 8888

          envFrom:
            - configMapRef:
                name: platform-config
            - configMapRef:
                name: config-server-config
            - secretRef:
                name: platform-secret

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8888

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8888
