apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: event-platform

nameSuffix: -config-server

resources:
  - ../../common/deployment
  - ../../common/service

patches:
  - path: deployment-patch.yaml
  - target:
      group: ""
      version: v1
      kind: Service
      name: app
    path: service-patch.json
