apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-service
  namespace: eventstream

  labels:
    app: order-service
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: eventstream

spec:
  replicas: 1

  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service
        app.kubernetes.io/name: order-service
        app.kubernetes.io/part-of: eventstream

    spec:
      containers:
        - name: order-service

          image: 226932643820.dkr.ecr.ap-south-1.amazonaws.com/eventstream/order-service:1.0.1

          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8081
              protocol: TCP

          env:

            - name: SERVER_PORT
              value: "8081"

            # Config Server
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"

            # Zipkin is intentionally not deployed in AWS.
            - name: MANAGEMENT_TRACING_ENABLED
              value: "false"

            # Eureka
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka/"

            # PostgreSQL
            - name: ORDER_DB_URL
              value: "jdbc:postgresql://postgres.eventstream-infra:5432/orders"

            - name: ORDER_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER

            - name: ORDER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres.eventstream-infra:5432/orders"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD

            # Pricing Service
            - name: PRICING_SERVICE_URL
              value: "http://pricing-service:8089"

            - name: PRICING_SERVICE_BASE_URL
              value: "http://pricing-service:8089"

            # Kafka
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.eventstream-infra:29092"

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.eventstream-infra:29092"

            # Kafka JSON trusted packages
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES
              value: "com.example.eventstream.common.*"

            # JVM
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError"

          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"

            limits:
              cpu: "750m"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http

            initialDelaySeconds: 50
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http

            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          securityContext:
            allowPrivilegeEscalation: false

            capabilities:
              drop:
                - ALL
