apiVersion: v1
kind: Secret

metadata:
  name: platform-secret
  namespace: event-platform

type: Opaque

stringData:
  JWT_SECRET: ${JWT_SECRET:MyVerySecretKeyForJwtAuthentication123456789}

  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: postgres
